version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  groups:
    prod:
      dependency-type: production
    dev:
      dependency-type: development
  commit-message:
    prefix: "chore(deps):"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore(deps):"