name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
inputs:
  github-token:
    description: "GitHub token"
    required: false
  allowed-commit-types:
    description: "Specify a comma separated list of allowed commit types"
    default: "build,chore,ci,docs,feat,fix,merge,perf,refactor,revert,style,test,wip"
    required: false
  include-pull-request-title:
    description: "Ensure the pull request title follows the conventional-commits standard"
    default: "false"
    required: false
  include-commits:
    description: "Ensure the commit messages follow the conventional-commits standard"
    default: "true"
    required: false

runs:
  using: node20
  main: dist/main/index.js
